# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reverse_tb',
                'doc_host': 'https://ababino.github.io',
                'git_url': 'https://github.com/ababino/reverse_tb',
                'lib_path': 'reverse_tb'},
  'syms': { 'reverse_tb.core': { 'reverse_tb.core.AutoFormattedReversedTB': ('core.html#autoformattedreversedtb', 'reverse_tb/core.py'),
                                 'reverse_tb.core.AutoFormattedReversedTB.structured_traceback': ( 'core.html#autoformattedreversedtb.structured_traceback',
                                                                                                   'reverse_tb/core.py'),
                                 'reverse_tb.core.reverse_tb': ('core.html#reverse_tb', 'reverse_tb/core.py'),
                                 'reverse_tb.core.reverse_tb_off': ('core.html#reverse_tb_off', 'reverse_tb/core.py'),
                                 'reverse_tb.core.reverse_tb_on': ('core.html#reverse_tb_on', 'reverse_tb/core.py'),
                                 'reverse_tb.core.reverse_traceback_ctx': ('core.html#reverse_traceback_ctx', 'reverse_tb/core.py')},
            'reverse_tb.on': {}}}
