# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reverse_tb',
                'doc_host': 'https://ababino.github.io',
                'git_url': 'https://github.com/ababino/reverse_tb',
                'lib_path': 'reverse_tb'},
  'syms': { 'reverse_tb.core': { 'reverse_tb.core.ReverseTB': ('core.html#reversetb', 'reverse_tb/core.py'),
                                 'reverse_tb.core.ReverseTB.text': ('core.html#reversetb.text', 'reverse_tb/core.py'),
                                 'reverse_tb.core.redirect_jupyter_stderr': ('core.html#redirect_jupyter_stderr', 'reverse_tb/core.py'),
                                 'reverse_tb.core.reverse_tb': ('core.html#reverse_tb', 'reverse_tb/core.py')}}}
